name: amf-m4
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.12
  - mafft=7.526
  - raxml-ng=1.2.2
  - epa-ng=0.3.8
  - pip
  - pip:
      - biopython==1.88
      - edlib==1.3.9.post1
